### ISSUE TITLE
Incompatibility with SSD1306 Libraries

### ISSUE THREAD

**Issue by Tim-Lorne** [WorldFamousElectronics/PulseSensorStarterProject#12]
The library does not seem to work with Adafruits SSD1306 Lib and causes init errors. I have removed the SD library and it still gives the same issue, it only seems to be a combo of the two libs causing the issue
https://pastebin.com/YKmY6H1F

**Comment by biomurph** [comment]
@Tim-Lorne 
The code you link to does not have your #include lines.
Can you post the error message you are getting?
I don't have code to talk to SSD1306 at hand, but I can compile the PulseSensor Playground with Adafruit_SSD1306.h and SD.h without any errors.
