### ISSUE TITLE
Why it says 600 bpm is ir because the sensor is amped? 

### ISSUE THREAD

**Issue by Polytox1210** [WorldFamousElectronics/PulseSensorStarterProject#14]
How can i know what bpm i habe when it says 500-600bpm? Can you help pls. Would divide the display out do the job?

**Comment by biomurph** [comment]
We need more information to help you. What Arduino hardware are you using? where are you placing the sensor on your body? Which sketch example are you using? Have you modified it? Please send us a picture of your physical set up so we can verify the pulse sensor
