### ISSUE TITLE
safety

### ISSUE THREAD

**Issue by CellaVie** [WorldFamousElectronics/PulseSensorStarterProject#19]
Hi,
can anyone tell me if Heart Rate sensors are electrical isolated from the Arduino power supply or is a battery power supply required

**Comment by biomurph** [comment]
@CellaVie 
That is a great question!
The Pulse Sensor is an optical heart monitor. It uses light, and is not supposed to be electrically connected to the body. 
Our kit has clear vinyl stickers that for over the sensor and protects the person (animal) and the sensor.
