### ISSUE TITLE
application to stm32f103r8t6

### ISSUE THREAD

**Issue by CesarPavon21** [WorldFamousElectronics/PulseSensorStarterProject#20]
I need help to implement the library with the stm32f103r8t6 through arduino ide.
The bpm value gives me zero, I think the problem is in the sampling time but I don't understand how to change it.

**Comment by biomurph** [comment]
@CesarPavon21 
Thanks for using PulseSensor.
I need some more information  in order to help you.
Please tell me what arduino board you are using? What version of Arduino IDE are you using?
Also, please send a picture of your hardware setup so that I can verify it.

**Comment by CesarPavon21** [comment]
Hello!
Thank you very much for your response.
I’m using the STM32F103R8T6 microcontroller and Arduino IDE 2.3.3.
I managed to solve it. I used a timer that generates interrupts every 2ms, but I have another question: in this way, it doesn't detect a bpm of zero at the moment when I stop placing my finger on the sensor.
Do you have any recommendations to improve real-time measurement?

**Comment by biomurph** [comment]
@CesarPavon21 
Glad you got it working.
Please share your code so that we can work your fix into our library?

I will need more information to help you. Please share your code?
Also, I am not quite sure what you mean when you say “doesn’t detect bpm of zero”.
Could you explain that more?

**Comment by CesarPavon21** [comment]
I need that when I don't have my finger on the sensor (in other words, it doesn't detect a pulse), the pulse value of “myBPM” in the program shows me zero, at least once.

This is the code with which I have made the sensor work with the STM32F103R8T6 microcontroller through Arduino IDE (Sorry for not being correctly commented each action): 

const int PULSE_INPUT = PA5;
int Threshold = 650; //550;
PulseSensorPlayground pulseSensor;
HardwareTimer *MyTim = new HardwareTimer(TIM2); //Generamos el la interrupcion a partir del Timer 2


void setup() {
  Serial.begin(115200);

  pulseSensor.analogInput(PULSE_INPUT);
  pulseSensor.setThreshold(Threshold);
  pulseSensor.begin();

  // Configura el temporizador TIM2 para disparar cada 2 ms
    MyTim->setOverflow(500);  // 500 Hz => 2 ms
    MyTim->attachInterrupt(onTimerInterrupt); // Asigna la función de interrupción
    MyTim->resume(); // Inicia el temporizador

}

void loop() {


}

void onTimerInterrupt() {
    // Coloca aquí el código de muestreo que quieras ejecutar cada 2 ms
    pulseSensor.sawNewSample();
    if (pulseSensor.sawStartOfBeat()) {            // Constantly test to see if "a beat happened".
      myBPM = pulseSensor.getBeatsPerMinute();  // Calls function on our pulseSensor object that returns BPM as an "int".
                                                 
    }

}

**Comment by biomurph** [comment]
@CesarPavon21 
Thanks for the code. I can use that to add support for STM32F103 in our library.

We don’t have code that outputs `0` for the BPM when there is no finger on it.
You could monitor the signal value and see if it is hovering around 1/2V (512 value of 10 bit ADC) and then ‘know’ that there is no finger on it.

Also, It is best to do as little as possible in the interrupt service routine. 
I suggest that you move the `if(pulseSensor.sawStartOfBeat` conditional into the loop.

**Comment by CesarPavon21** [comment]
Understood. Thank you very much for the advice and for the continued response.
