### ISSUE TITLE
Data interpretation 

### ISSUE THREAD

**Issue by beto24** [WorldFamousElectronics/PulseSensorStarterProject#3]
I was just wondering if I could get some assistance or suggestions as to how to determine the actual BPM from the output data. I made and excel graph (Frequency vs Time)--- where I am not sure if the increments in time are in milliseconds or something else. Keeping in mind that the threshold is maintained at 550, and with the data obtained, I seem to be getting numbers around 250 BPM (while a person is at rest). For example, the time difference between areas that surpass the 550 threshold is as such: t(2) = 401, t(1) = 378; t(2)-t(1) = 23 milliseconds which translates to 0.00038 (min)--- and so 1/.00038 = 2600 BPM??
I may just be misinterpreting the data and would greatly appreciate some help.
Thank you

**Comment by yury-g** [comment]
Hi Beto, 
This project does not give you BPM.  PulseSensorStarterProject simply shows you the raw signal. 

To get BPM, you want to use this code: [https://github.com/WorldFamousElectronics/PulseSensor_Amped_Arduino](https://github.com/WorldFamousElectronics/PulseSensor_Amped_Arduino)

Project page with discussion regarding your question is here:
[https://pulsesensor.com/pages/getting-advanced](https://pulsesensor.com/pages/getting-advanced)
