### ISSUE TITLE
I somehow can't get any good data

### ISSUE THREAD

**Issue by victoroos** [WorldFamousElectronics/PulseSensorStarterProject#4]
Hi

After connecting the heartbeat sensor, I'm now trying to get data from it. However, it just spikes a bit, not even looking like a beating heart. The sensor lights up green so it is connected..
Any tips?
vkr
victor

**Comment by biomurph** [comment]
Victor,
I will need more information from you to help troubleshoot this problem. Can you send a picture of the sensor? What Arduino board are you using? How are you visualizing the data?

**Comment by victoroos** [comment]
sensor as the hardbeat sensor? SUre, will do in a few. For the other questions: Uno. And using the serial plotter as instructed.

**Comment by biomurph** [comment]
also send a screen shot of the data in the serial plotter

**Comment by victoroos** [comment]
![wp_20171019_09_25_16_pro](https://user-images.githubusercontent.com/28945224/31758898-99696806-b4af-11e7-86c7-6d79048de54e.jpg)

**Comment by victoroos** [comment]
![screenshot 1](https://user-images.githubusercontent.com/28945224/31758911-a981e2ae-b4af-11e7-8314-9a872f0a20b6.png)

**Comment by victoroos** [comment]
Can you break the sensor when attach it wrong on accident, because that is what the store where I bought it is telling me. I was confused by the grey and white, which both were neutral I thought.

**Comment by biomurph** [comment]
Well, it looks like you purchased a counterfeit Pulse Sensor. That is not our PCB, nor is it our wire type and color. I'm sorry, but since I don't have any idea what's going on with that hardware I can't troubleshoot this problem for you. 

Please support the Original Makers of Pulse Sensor by purchasing from a legitimate reseller.
www.pulsesensor.com
www.adafruit.com
www.sparkfun.com

**Comment by victoroos** [comment]
I didn't even know that was an option, you might wanna contact https://www.hackerstore.nl/ about it, they are a legitamate company, maybe they don't know about it either, but yes I will support you guys
Thanks! :)

**Comment by yury-g** [comment]
Thank you!
