### ISSUE TITLE
MKRZERO not compiling

### ISSUE THREAD

**Issue by piver06** [WorldFamousElectronics/PulseSensorStarterProject#6]
Hi, 
I'm using an arduino MKRZERO but it doesn't want to compile the PulseSensor_BPM or PulseSensor_BPM_Alternative examples. It seems to be complaining about interrupts. The USE_ARDUINO_INTERRUPTS is true for the PulseSensor_BPM and false for the PulseSensor_BPM_Alternative. I was wondering if i had to modify anything else?
Thank you.

**Comment by biomurph** [comment]
Thanks for the heads up.
I made a change in the library so that it will compile for MKRZERO.
Please re-download the library or update it in Arduino LIbraries Manager.
You will have to use the PulseSensor_BPM_Alternative, as we do not yet support MKRZERO interrupts.

**Comment by aloysiusnzh** [comment]
Hi, I have the same issue with the sparkfun pro micro. Is it not compatible with the pulse sensor and servo working together?

**Comment by biomurph** [comment]
@aloysiusnzh 
Please start a new issue thread. your comment is not relevant on this one.
Please use the [PulseSensor Playground Library](https://github.com/WorldFamousElectronics/PulseSensorPlayground), as that is the most up-to-date and supports the most hardware platforms.
