### ISSUE TITLE
STOP PulseSensor

### ISSUE THREAD

**Issue by AiWOL** [WorldFamousElectronics/PulseSensorStarterProject#7]
Command PulseSensorPlayground.:begin() to START sequence.
How do I STOP the execution PulseSensor sequence?

**Comment by biomurph** [comment]
hmm, it looks like you are posting this issue on the wrong code repo.
It's a good question, but it belongs in the PulseSesnor Playground repo. Please re-post it there and we will try to integrate your idea into the library.
