### ISSUE TITLE
Can arduino nano be used? Sketch size too high.

### ISSUE THREAD

**Issue by nabjitu** [WorldFamousElectronics/PulseSensorStarterProject#8]
I'm using an Arduino nano and having following problem. So far i can see Arduino uno and nano has the same SRAM of 2 KB. Is the problem really that I'm using a Arduino nano?

"Build options changed, rebuilding all
Sketch uses 2250 bytes (15%) of program storage space. Maximum is 14336 bytes.
Global variables use 190 bytes (18%) of dynamic memory, leaving 834 bytes for local variables. Maximum is 1024 bytes.
avrdude: ser_open(): can't open device "COM1": No such file or directory
Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions."

**Comment by biomurph** [comment]
It looks like you are choosing the wrong serial port. Try different ports in your drop down menu, and make sure that you have the latest ftdi driver
